### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by avnes**

### CODE REVIEW

**Comment by wcarlsen** [comment]
@rifisdfds and @samidbb ?

**Comment by samidbb** [comment]
Shall we keep it as it is? wouldn't it be part of what you mentioned by "avoiding copy-and-paste" so people have to think a bit ;)  what do you think @rifisdfds ?

**Comment by rifisdfds** [comment]
I think I would prefer people to think and prompt for the question about whether you can change the name of the provider

**Comment by avnes** [comment]
@samidbb and @rifisdfds - Thanks for your feedback on this PR. I have now updated this PR to keep encouraging people to think. Since the updated version of the provider change over time, this updated PR also encourge people to find the new version number, so a link to the docs have been added. I hope this addresses your concerns.

**Review by rifisdfds — APPROVED** [review]

**Pull request merged**
